# Generated by Django 2.2.3 on 2019-08-20 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tag',
            field=models.ManyToManyField(related_name='tags', to='item.Tag'),
        ),
    ]
