# Generated by Django 2.2.3 on 2019-08-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_item_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tag',
            field=models.ManyToManyField(related_name='items', to='item.Tag'),
        ),
    ]
