# Generated by Django 2.2.3 on 2019-08-29 07:59

from django.db import migrations, models
import item.models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0013_auto_20190820_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to=item.models.get_item_image_path),
        ),
    ]
